**NumPy**

In [ ]:
import numpy as np
ar=np.arange(1,21)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
ar0=np.zeros(10)
print(ar0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
ar1=np.ones(8)
print(ar1)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
ar2=np.arange(2,21,2)
print(ar2)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np
ar4=np.array([[1,2,3,4],[5,6,7,8]])
print(ar4.ndim)
print(ar4.shape)
print(ar4.size)
print(ar4.dtype)

2
(2, 4)
8
int64


In [ ]:
import numpy as np
ar6=np.array([1,2,3,4])
print(ar6*2)

[2 4 6 8]


In [ ]:
import numpy as np
ar7=np.array([[1,2,3],[4,5,6]])
print(ar7**2)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
import numpy as np
ar8=np.array([10,20,30,40,50])
print(ar8/10)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
ar9=np.array([1,2,3,4,5])
print(np.sum(ar9))
print(np.mean(ar9))
print(np.max(ar9))
print(np.min(ar9))

15
3.0
5
1


In [ ]:
import numpy as np
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print(np.concatenate([ar1,ar2]))

[1 2 3 4 5 6]


**Pandas**

In [ ]:
import pandas as pd
df=pd.DataFrame({"SNo":[1,2,3],"Name":["A","B","C"]})
print(df)

   SNo Name
0    1    A
1    2    B
2    3    C


In [13]:
import pandas as pd
df=pd.read_csv('/content/students.csv')
print("Top 5 rows")
print(df.head(5))
print("Last 5 rows")
print(df.tail(5))
print("Column Names")
print(df.columns)
print(df.info())

Top 5 rows
   studentid          name  age  gender class  marks           city  \
0       1001  Aarav Sharma   15    Male   10A     88      Hyderabad   
1       1002    Ananya Rao   14  Female    9B     92     Vijayawada   
2       1003   Rahul Verma   16    Male   10B     76      Hyderabad   
3       1004   Sneha Reddy   15  Female   10A     85  Visakhapatnam   
4       1005   Kiran Kumar   14    Male    9A     81         Guntur   

                      email  
0  aarav.sharma@example.com  
1    ananya.rao@example.com  
2   rahul.verma@example.com  
3   sneha.reddy@example.com  
4   kiran.kumar@example.com  
Last 5 rows
   studentid          name  age  gender class  marks       city  \
5       1006    Priya Nair   15  Female   10C     95  Hyderabad   
6       1007   Arjun Patel   16    Male   11A     78   Warangal   
7       1008   Meera Joshi   14  Female    9C     89  Hyderabad   
8       1009  Vikram Singh   15    Male   10B     83   Tirupati   
9       1010   Divya Gupta   16  Fe

In [ ]:
marks_info=df[df['marks']>85]
print(marks_info)

   studentid          name  age  gender class  marks        city  \
0       1001  Aarav Sharma   15    Male   10A     88   Hyderabad   
1       1002    Ananya Rao   14  Female    9B     92  Vijayawada   
5       1006    Priya Nair   15  Female   10C     95   Hyderabad   
7       1008   Meera Joshi   14  Female    9C     89   Hyderabad   
9       1010   Divya Gupta   16  Female   11B     91   Hyderabad   

                      email  
0  aarav.sharma@example.com  
1    ananya.rao@example.com  
5    priya.nair@example.com  
7   meera.joshi@example.com  
9   divya.gupta@example.com  


In [ ]:
df1=df[df['city']=='Hyderabad']
print(df1)

   studentid          name  age  gender class  marks       city  \
0       1001  Aarav Sharma   15    Male   10A     88  Hyderabad   
2       1003   Rahul Verma   16    Male   10B     76  Hyderabad   
5       1006    Priya Nair   15  Female   10C     95  Hyderabad   
7       1008   Meera Joshi   14  Female    9C     89  Hyderabad   
9       1010   Divya Gupta   16  Female   11B     91  Hyderabad   

                      email  
0  aarav.sharma@example.com  
2   rahul.verma@example.com  
5    priya.nair@example.com  
7   meera.joshi@example.com  
9   divya.gupta@example.com  


In [ ]:
df2=df[df['gender']=='Male']
print(df2)

   studentid          name  age gender class  marks       city  \
0       1001  Aarav Sharma   15   Male   10A     88  Hyderabad   
2       1003   Rahul Verma   16   Male   10B     76  Hyderabad   
4       1005   Kiran Kumar   14   Male    9A     81     Guntur   
6       1007   Arjun Patel   16   Male   11A     78   Warangal   
8       1009  Vikram Singh   15   Male   10B     83   Tirupati   

                      email  
0  aarav.sharma@example.com  
2   rahul.verma@example.com  
4   kiran.kumar@example.com  
6   arjun.patel@example.com  
8  vikram.singh@example.com  


In [ ]:
df3=df.groupby('city')['marks'].mean().sort_values(ascending=False)
print("City wise average marks")
print(df3)
print(df3.head(1))

City wise average marks
city
Vijayawada       92.0
Hyderabad        87.8
Visakhapatnam    85.0
Tirupati         83.0
Guntur           81.0
Warangal         78.0
Name: marks, dtype: float64
city
Vijayawada    92.0
Name: marks, dtype: float64
